// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

var prefixUrlCacheKey = "cache:url:"

type urlModel interface {
	Insert(ctx context.Context, data *Url) error
	FindOne(ctx context.Context, id string) (*Url, error)
	Update(ctx context.Context, data *Url) error
	Delete(ctx context.Context, id string) error
}

type defaultUrlModel struct {
	conn *monc.Model
}

func newDefaultUrlModel(conn *monc.Model) *defaultUrlModel {
	return &defaultUrlModel{conn: conn}
}

func (m *defaultUrlModel) Insert(ctx context.Context, data *Url) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixUrlCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return err
}

func (m *defaultUrlModel) FindOne(ctx context.Context, id string) (*Url, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Url
	key := prefixUrlCacheKey + id
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUrlModel) Update(ctx context.Context, data *Url) error {
	data.UpdateAt = time.Now()
	key := prefixUrlCacheKey + data.ID.Hex()
	_, err := m.conn.ReplaceOne(ctx, key, bson.M{"_id": data.ID}, data)
	return err
}

func (m *defaultUrlModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	key := prefixUrlCacheKey + id
	_, err = m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return err
}
